name: Reusable Go Release Workflow

on:
  workflow_call:
    inputs:
      go_version:
        description: 'Go version to use'
        required: false
        type: string
        default: '1.23'
      binary_name:
        description: 'Name of the binary to build'
        required: true
        type: string
      main_path:
        description: 'Path to main.go (e.g., ./cmd/myapp)'
        required: false
        type: string
        default: '.'
      bump_type:
        description: 'Version bump type (major, minor, patch)'
        required: true
        type: string
      enable_docker:
        description: 'Enable Docker image building'
        required: false
        type: boolean
        default: false
      docker_platforms:
        description: 'Docker platforms to build'
        required: false
        type: string
        default: 'linux/amd64,linux/arm64'
    secrets:
      GITHUB_TOKEN:
        required: true

permissions:
  contents: write
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io

jobs:
  create-release:
    name: Create Tag and Release
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
      version: ${{ steps.tag.outputs.new_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
          cache: true

      - name: Bump version and create tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ inputs.bump_type }}
          TAG_PREFIX: v
          VERBOSE: true
          WITH_V: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        if: steps.tag.outputs.new_tag != ''
        with:
          version: latest
          distribution: goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: create-release
    if: inputs.enable_docker && needs.create-release.outputs.new_tag != ''
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.create-release.outputs.new_tag }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.create-release.outputs.new_tag }}
            type=semver,pattern={{major}},value=${{ needs.create-release.outputs.new_tag }}
            type=raw,value=latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Lowercase repository name
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: ${{ inputs.docker_platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache
          cache-to: |
            type=gha,mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:cache,mode=max
          provenance: true
          sbom: true
          build-args: |
            BUILDKIT_INLINE_CACHE=1
            VERSION=${{ needs.create-release.outputs.new_tag }}
