# Enhanced GoReleaser Configuration Template
# Based on actual convention from pm-agent-workflow and mcp-trino
# Copy to your repository root and customize as needed

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: '{{ .ProjectName }}'  # Customize: your binary name (e.g., pagent, mcp-trino)
    main: .  # Customize: your main package path (e.g., ./cmd/pagent, ./cmd)
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      # - windows  # Uncomment if you need Windows support
    goarch:
      - amd64
      - arm64
      # - arm     # Uncomment if you need ARM v6/v7 support
    # goarm:      # Uncomment if you enabled arm above
    #   - "6"
    #   - "7"
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats:
      - tar.gz

snapshot:
  version_template: "{{ incpatch .Version }}-next"

# Enhanced changelog with conventional commits support
# This is the key improvement over the basic configuration
changelog:
  use: github
  sort: asc
  abbrev: 7

  # Group commits by type (conventional commits)
  groups:
    - title: 🚀 Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 🐛 Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 📚 Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 🎨 Styling
      regexp: '^.*?style(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: ♻️ Refactoring
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: ⚡ Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 5
    - title: ✅ Tests
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 6
    - title: 🔧 Build System
      regexp: '^.*?build(\([[:word:]]+\))??!?:.+$'
      order: 7
    - title: 👷 CI/CD
      regexp: '^.*?ci(\([[:word:]]+\))??!?:.+$'
      order: 8
    - title: 🔨 Other Changes
      order: 999

  filters:
    # Exclude commits that are noise (not user-facing changes)
    exclude:
      - '^chore:'
      - '^chore\('
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

# Release configuration
release:
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
