# Minimal Release Workflow
# Copy to .github/workflows/release.yml
# Uses the reusable workflow from tuannvm/.github repository

name: Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    uses: tuannvm/.github/.github/workflows/release-go.yml@main
    with:
      go_version: '1.25'
      binary_name: ${{ github.event.repository.name }}
      main_path: './cmd'
      bump_type: ${{ inputs.bump_type }}
      enable_docker: true
      docker_platforms: 'linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
